cifar10_path: ~/scratch/data/CIFAR10
cifar100_path: ~/scratch/data/CIFAR100
train_imagenet_path: /jobtmp/ssunda11/ImageNet/train
val_imagenet_path: /jobtmp/ssunda11/ImageNet/val
data_env_config: /users/ssunda11/Learning-Factored-Representation-via-SSL/configs/data_generator/config.yaml
