policy_head:
  algorithm: "PPO"  # Options: DQN, PPO, A2C
  num_models: 3
  train_interval: 1000000
  # eval_interval: 1
  verbose: true
  gif_log_freq: 20000
  reward_log_freq: 2000
  save_weight_freq: 20000


  ppo:
    n_steps: 1000
    n_epochs: 20
    learning_rate: 0.0008
    batch_size: 64
    gamma: 0.99
    gae_lambda: 0.96
    clip_range: 0.2
    clip_range_vf: null
    normalize_advantage: True
    ent_coef: 0.01
    max_grad_norm: 0.5
    target_kl: null
    verbose: null
    gae_lambda: null
    seed: null

  dqn:
    buffer_size: 500000
    learning_starts: 10
    batch_size: 32
    learning_rate: 0.000005
    gradient_steps: 16
    tau: 0.8
    gamma: 0.99
    train_freq: 1
    exploration_fraction: 0.1
    exploration_final_eps: 0.1
    #max_grad_norm: 10
    seed: null

  a2c:
    learning_rate: 0.0003
    n_steps: 5
    gamma: 0.99
    ent_coef: 0.01
    vf_coef: 0.5
    max_grad_norm: 0.5
    rms_prop_eps: 1e-5
    gae_lambda: 0.95
    normalize_advantage: True
    seed: null