defaults:
  - /user/vipul@local_data_path: data_paths
  - /user/vipul@_global_: logging
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: 3090-gcondo
    timeout_min: 60
    max_num_timeout: 1
    mem_gb: 80

batch_size_across_gpus: 256

hardware:
  world_size: 1

optim:
  epochs: 1
  max_steps: 2
