# @package _global_

defaults:
  - _self_
  - /user@_global_: vsharm44/run_slurm

hydra:
  launcher:
    tasks_per_node: ${hardware.world_size}
    gpus_per_node: ${hardware.world_size}
    cpus_per_task: 6
    mem_gb: 30
    timeout_min: 600
    max_num_timeout: 10

batch_size_across_gpus: 256


data:
  train_on: base
  base:
    name: CustomDataset
    data_env_config: ${local_data_path.data_env_config}
    limit: 50000
    policy_model: null
    model_path: null
    mode: cont
    # path: ${local_data_path.cifar10_path}
    batch_size: ${batch_size_across_gpus}
    drop_last: True
    shuffle: True
    split: train
    num_workers: -1
    transforms:
      view1:
      - name: RandomResizedCrop
        kwargs:
          size: 64
          scale:
            - 0.2
            - 1.0
          interpolation: bicubic
      - name: RandomHorizontalFlip
        kwargs:
          p: 0.5
      - name: ColorJitter
        kwargs:
          brightness: 0.4
          contrast: 0.4
          saturation: 0.2
          hue: 0.1
        p: 0.8
      - name: RandomGrayscale
        kwargs:
          p: 0.2
  test_out:
    name: CustomDataset
    data_env_config: ${local_data_path.data_env_config}
    policy_model: null
    model_path: null
    limit: 10000
    mode: cont
    # path: ${local_data_path.cifar10_path}
    batch_size: ${batch_size_across_gpus}
    drop_last: False
    num_workers: -1
    split: test
    transforms:
      view1:
      - name: Identity

model:
  name: Supervised
  backbone_model: resnet50
  sync_batchnorm: false
  memory_format: contiguous_format

optim:
  epochs: 1000
  lr: 1
  optimizer: LARS
  weight_decay: 1e-6

hardware:
  seed: 0
  float16: true
  gpu_id: 0
  world_size: 1

log:
  save_final_model: true
  eval_every_epoch: 20
  log_every_step: 150
